spring:
  task:
    report: 10
  rabbitmq:
    #    host: 101.42.224.110
    host: localhost
    port: 5672
    username: guest
    password: guest
    #    Exchange、Queue确认应答
    publisher-confirm-type: correlated
    #    返回信息给Producer
    publisher-returns: on
  datasource:
    #    url: jdbc:mysql://101.42.224.110:3306/user
    url: jdbc:mysql://localhost:3306/user
    username: root
    #    password: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      auto-commit: false
      validation-timeout: 3000
      max-lifetime: 60000
      connection-timeout: 3000
  redis:
    port: 6379
    #    host: 101.42.224.110
    host: localhost
    database: 0
  config:
    activate:
      on-profile: default
server:
  port: 8081

